import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/ui/header/Header";
import Layout from "@/components/Layout";
import Navbar from "@/components/ui/Navbar";

const geistSans = localFont({
  src: "./fonts/AirbnbCerealWMd.woff",
  variable: "--airbnb-cereal-md",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased text-slate-800`}>
        <Layout>
          <Header />
          <Navbar />
          {children}
        </Layout>
      </body>
    </html>
  );
}
